-- ============================================================
-- SQL Server DDL Script
-- Generated by domain-model-sql-generator
-- Source: /sanjel/PRG/orgModel/01 - Program Request Management/domain-model-metadata.json
-- Generated: 2026-03-11T09:09:50.228Z
-- ============================================================

USE [$(DatabaseName)];
GO

SET NOCOUNT ON;
GO

-- ============================================================

-- ENTITY TABLES

-- ============================================================

-- Program request submitted for engineering work with complete lifecycle tracking
CREATE TABLE [dbo].[requests] (
    [request_id]           NVARCHAR(64)   NOT NULL,
    [status]               INT            NOT NULL,
    [created_date]         DATETIME2      NOT NULL,
    [priority]             INT            NOT NULL,
    [client_id]            NVARCHAR(64)   NOT NULL,
    [source_email]         NVARCHAR(256)  NOT NULL,
    [assigned_engineer_id] NVARCHAR(64)   NOT NULL,
    [assigned_by]          NVARCHAR(256)  NOT NULL,
    [acknowledgment_date]  DATETIME2      NOT NULL,
    [completion_date]      DATETIME2      NOT NULL,
    -- Audit columns
    [created_at]          DATETIME2      NOT NULL  CONSTRAINT [DF_requests_created_at]  DEFAULT GETUTCDATE(),
    [created_by]          NVARCHAR(256)  NOT NULL  CONSTRAINT [DF_requests_created_by]  DEFAULT N'',
    [updated_at]          DATETIME2          NULL,
    [updated_by]          NVARCHAR(256)      NULL,
    CONSTRAINT [PK_requests] PRIMARY KEY ([request_id])
);

CREATE NONCLUSTERED INDEX [IX_requests_client_id]
    ON [dbo].[requests] ([client_id]);
CREATE NONCLUSTERED INDEX [IX_requests_assigned_engineer_id]
    ON [dbo].[requests] ([assigned_engineer_id]);

-- Engineering staff member who processes requests and develops technical solutions
CREATE TABLE [dbo].[engineers] (
    [engineer_id]          NVARCHAR(64)   NOT NULL,
    [name]                 NVARCHAR(256)  NOT NULL,
    [email]                NVARCHAR(256)  NOT NULL,
    [team]                 NVARCHAR(256)  NOT NULL,
    [workload_capacity]    INT            NOT NULL,
    [availability_status]  INT            NOT NULL,
    -- Audit columns
    [created_at]          DATETIME2      NOT NULL  CONSTRAINT [DF_engineers_created_at]  DEFAULT GETUTCDATE(),
    [created_by]          NVARCHAR(256)  NOT NULL  CONSTRAINT [DF_engineers_created_by]  DEFAULT N'',
    [updated_at]          DATETIME2          NULL,
    [updated_by]          NVARCHAR(256)      NULL,
    CONSTRAINT [PK_engineers] PRIMARY KEY ([engineer_id])
);

CREATE TABLE [dbo].[managers] (
    [manager_id]           NVARCHAR(64)   NOT NULL,
    [name]                 NVARCHAR(256)  NOT NULL,
    [email]                NVARCHAR(256)  NOT NULL,
    -- Audit columns
    [created_at]          DATETIME2      NOT NULL  CONSTRAINT [DF_managers_created_at]  DEFAULT GETUTCDATE(),
    [created_by]          NVARCHAR(256)  NOT NULL  CONSTRAINT [DF_managers_created_by]  DEFAULT N'',
    [updated_at]          DATETIME2          NULL,
    [updated_by]          NVARCHAR(256)      NULL,
    CONSTRAINT [PK_managers] PRIMARY KEY ([manager_id])
);

CREATE TABLE [dbo].[data_elements] (
    [element_id]           NVARCHAR(64)   NOT NULL,
    [request_id]           NVARCHAR(64)   NOT NULL,
    [element_type]         INT            NOT NULL,
    [raw_value]            NVARCHAR(256)  NOT NULL,
    [validated_value]      NVARCHAR(256)  NOT NULL,
    [validation_status]    INT            NOT NULL,
    [source_location]      NVARCHAR(256)  NOT NULL,
    [validation_notes]     NVARCHAR(MAX)  NOT NULL,
    -- Audit columns
    [created_at]          DATETIME2      NOT NULL  CONSTRAINT [DF_data_elements_created_at]  DEFAULT GETUTCDATE(),
    [created_by]          NVARCHAR(256)  NOT NULL  CONSTRAINT [DF_data_elements_created_by]  DEFAULT N'',
    [updated_at]          DATETIME2          NULL,
    [updated_by]          NVARCHAR(256)      NULL,
    CONSTRAINT [PK_data_elements] PRIMARY KEY ([element_id])
);

CREATE NONCLUSTERED INDEX [IX_data_elements_request_id]
    ON [dbo].[data_elements] ([request_id]);

CREATE TABLE [dbo].[state_diagrams] (
    [diagram_id]           NVARCHAR(64)   NOT NULL,
    [diagram_name]         NVARCHAR(256)  NOT NULL,
    [file_path]            NVARCHAR(256)  NOT NULL,
    [version]              NVARCHAR(256)  NOT NULL,
    [import_date]          DATETIME2      NOT NULL,
    [parsing_confidence]   FLOAT          NOT NULL,
    [client_id]            NVARCHAR(64)   NOT NULL,
    [diagram_type]         INT            NOT NULL,
    -- Audit columns
    [created_at]          DATETIME2      NOT NULL  CONSTRAINT [DF_state_diagrams_created_at]  DEFAULT GETUTCDATE(),
    [created_by]          NVARCHAR(256)  NOT NULL  CONSTRAINT [DF_state_diagrams_created_by]  DEFAULT N'',
    [updated_at]          DATETIME2          NULL,
    [updated_by]          NVARCHAR(256)      NULL,
    CONSTRAINT [PK_state_diagrams] PRIMARY KEY ([diagram_id])
);

CREATE NONCLUSTERED INDEX [IX_state_diagrams_client_id]
    ON [dbo].[state_diagrams] ([client_id]);

CREATE TABLE [dbo].[review_packages] (
    [package_id]           NVARCHAR(64)   NOT NULL,
    [request_id]           NVARCHAR(64)   NOT NULL,
    [submitting_engineer_id] NVARCHAR(64)   NOT NULL,
    [assigned_reviewer_id] NVARCHAR(64)   NOT NULL,
    [submission_date]      DATETIME2      NOT NULL,
    [review_completion_date] DATETIME2      NOT NULL,
    [review_status]        INT            NOT NULL,
    [work_summary]         NVARCHAR(MAX)  NOT NULL,
    [review_feedback]      NVARCHAR(MAX)  NOT NULL,
    -- Audit columns
    [created_at]          DATETIME2      NOT NULL  CONSTRAINT [DF_review_packages_created_at]  DEFAULT GETUTCDATE(),
    [created_by]          NVARCHAR(256)  NOT NULL  CONSTRAINT [DF_review_packages_created_by]  DEFAULT N'',
    [updated_at]          DATETIME2          NULL,
    [updated_by]          NVARCHAR(256)      NULL,
    CONSTRAINT [PK_review_packages] PRIMARY KEY ([package_id])
);

CREATE NONCLUSTERED INDEX [IX_review_packages_request_id]
    ON [dbo].[review_packages] ([request_id]);
CREATE NONCLUSTERED INDEX [IX_review_packages_submitting_engineer_id]
    ON [dbo].[review_packages] ([submitting_engineer_id]);
CREATE NONCLUSTERED INDEX [IX_review_packages_assigned_reviewer_id]
    ON [dbo].[review_packages] ([assigned_reviewer_id]);

-- System-generated communication to stakeholders about request status and actions
CREATE TABLE [dbo].[notifications] (
    [notification_id]      NVARCHAR(64)   NOT NULL,
    [request_id]           NVARCHAR(64)   NOT NULL,
    [recipient_type]       INT            NOT NULL,
    [notification_type]    INT            NOT NULL,
    [delivery_method]      INT            NOT NULL,
    [sent_date]            DATETIME2      NOT NULL,
    [content]              NVARCHAR(MAX)  NOT NULL,
    -- Audit columns
    [created_at]          DATETIME2      NOT NULL  CONSTRAINT [DF_notifications_created_at]  DEFAULT GETUTCDATE(),
    [created_by]          NVARCHAR(256)  NOT NULL  CONSTRAINT [DF_notifications_created_by]  DEFAULT N'',
    [updated_at]          DATETIME2          NULL,
    [updated_by]          NVARCHAR(256)      NULL,
    CONSTRAINT [PK_notifications] PRIMARY KEY ([notification_id])
);

CREATE NONCLUSTERED INDEX [IX_notifications_request_id]
    ON [dbo].[notifications] ([request_id]);


-- ============================================================
-- END OF DDL SCRIPT
-- ============================================================
